In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns
import tensorflow as tf
import keras
from sklearn.model_selection import train_test_split
from tensorflow.python.keras.layers.convolutional import Conv1D, MaxPooling1D
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.layers import ConvLSTM2D
from keras.utils import to_categorical
import pickle
import os
import NN

import dataset_utils
import importlib
import matplotlib
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.ticker import LinearLocator
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Conv3D, MaxPooling3D, Embedding, LSTM, Bidirectional, Reshape, Concatenate

In [36]:
DATA_DIR = "3_class_data"
NUM_POINTS = 100
NUM_CLASSES = 2
BATCH_SIZE = 32
train_points, test_points, train_labels, test_labels, CLASS_MAP = dataset_utils.parse_dataset(NUM_POINTS, DATA_DIR)

processing class: jumping
processing class: speedwalking
processing class: walking


In [37]:
print(test_labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [38]:
print(train_points)

[[[ 7.437e-01  6.938e-01  2.361e-01  5.010e-01  2.500e+02]
  [ 3.042e-01  0.000e+00  3.391e-02  7.515e-01  1.530e+02]
  [ 1.003e-01  0.000e+00  1.000e+00  6.260e-01  3.340e+02]
  ...
  [ 1.000e+00  8.105e-01  2.267e-01  3.757e-01  3.050e+02]
  [ 8.950e-01  3.061e-02  9.751e-01 -2.505e-01  2.630e+02]
  [ 8.442e-01  5.000e-01  5.181e-01 -3.757e-01  2.740e+02]]

 [[ 6.929e-01  5.410e-01  2.374e-01  3.757e-01  2.820e+02]
  [ 0.000e+00  4.932e-01  0.000e+00  8.765e-01  3.000e+02]
  [ 0.000e+00  4.058e-01  4.167e-01 -5.010e-01  3.220e+02]
  ...
  [ 6.997e-01  6.001e-01  7.402e-01 -8.765e-01  2.780e+02]
  [ 1.000e+00  7.271e-01  2.203e-02 -6.260e-01  1.720e+02]
  [ 5.723e-01  8.076e-01  3.647e-01 -1.002e+00  2.630e+02]]

 [[ 0.000e+00  3.384e-01  3.237e-01 -2.505e-01  3.210e+02]
  [ 7.144e-01  8.481e-01  5.039e-01  1.252e-01  2.190e+02]
  [ 5.371e-01  6.885e-01  6.777e-01 -1.252e-01  2.510e+02]
  ...
  [ 1.715e-01  5.728e-01  7.139e-01 -5.010e-01  3.500e+02]
  [ 4.841e-01  2.037e-01  7.124e-0

In [59]:
print(train_points.shape)
print(test_points.shape)
print(train_labels.shape)
print(test_labels.shape)

(638, 100, 5)
(162, 100, 5)
(638,)
(162,)


In [40]:
from tensorflow import data as tf_data
import keras
#import PointNET

keras.utils.set_random_seed(seed=42)

In [71]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization

# Define the input shape (5 features)
sequence_length = 100  # Example: Fixed sequence length of 100 timesteps

input_shape = (sequence_length, 5)

# Define the model
model = models.Sequential()

# 1. CNN layers
model.add(layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=input_shape))
model.add(layers.MaxPooling1D(pool_size=2))
# model.add(layers.Conv1D(filters=128, kernel_size=3, activation='relu'))
# model.add(layers.MaxPooling1D(pool_size=2))

# 2. Flatten the output before feeding into Dense layers
model.add(layers.Flatten())

# 3. Fully connected layer
model.add(layers.Dense(64, activation='relu'))

model.add(layers.Dense(3, activation='softmax'))


In [72]:
# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Summary of the model
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_20 (Conv1D)          (None, 98, 64)            1024      
                                                                 


 max_pooling1d_20 (MaxPooli  (None, 49, 64)            0         
 ng1D)                                                           
                                                                 
 flatten_12 (Flatten)        (None, 3136)              0         
                                                                 
 dense_19 (Dense)            (None, 64)                200768    
                                                                 
 dense_20 (Dense)            (None, 3)                 195       
                                                                 
Total params: 201987 (789.01 KB)
Trainable params: 201987 (789.01 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [74]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3)
# training
history = model.fit(train_points, train_labels, epochs=30, batch_size=32, validation_data=(test_points, test_labels), verbose=1, callbacks=[early_stopping])

Epoch 1/30
20/20 [==============================] - 1s 40ms/step - loss: 1.1763 - accuracy: 0.6301 - val_loss: 3.6920 - val_accuracy: 0.2963
Epoch 2/30
20/20 [==============================] - 0s 10ms/step - loss: 0.9728 - accuracy: 0.6912 - val_loss: 4.7199 - val_accuracy: 0.3272
Epoch 3/30
20/20 [==============================] - 0s 10ms/step - loss: 0.7617 - accuracy: 0.7335 - val_loss: 3.5104 - val_accuracy: 0.3210
Epoch 4/30
20/20 [==============================] - 0s 8ms/step - loss: 0.5790 - accuracy: 0.7712 - val_loss: 4.2853 - val_accuracy: 0.3086
Epoch 5/30
20/20 [==============================] - 0s 8ms/step - loss: 0.5744 - accuracy: 0.7884 - val_loss: 3.4457 - val_accuracy: 0.3086
Epoch 6/30
20/20 [==============================] - 0s 7ms/step - loss: 0.3839 - accuracy: 0.8480 - val_loss: 3.4716 - val_accuracy: 0.3025
Epoch 7/30
20/20 [==============================] - 0s 8ms/step - loss: 0.5108 - accuracy: 0.7727 - val_loss: 3.7508 - val_accuracy: 0.2963
Epoch 8/30
20/20 

In [70]:
test_loss, test_acc = model.evaluate(test_points, test_labels, verbose=1)

6/6 [==============================] - 0s 6ms/step - loss: 1.6617 - accuracy: 0.3148
