In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns
import tensorflow as tf
import keras
from sklearn.model_selection import train_test_split
from tensorflow.python.keras.layers.convolutional import Conv1D, MaxPooling1D
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.layers import ConvLSTM2D
from keras.utils import to_categorical
import pickle
import os
import NN

In [2]:
import dataset_utils
import importlib

In [14]:
importlib.reload(dataset_utils)

<module 'dataset_utils' from 'd:\\University\\P4P\\P4P-mmWave\\MMWave_Radar_Human_Tracking_and_Fall_detection\\dataset_utils.py'>

In [3]:
DATA_DIR = "pointnet_data"
NUM_POINTS = 100
NUM_CLASSES = 2
BATCH_SIZE = 32
train_points, test_points, train_labels, test_labels, CLASS_MAP = dataset_utils.parse_dataset(NUM_POINTS, DATA_DIR)

processing class: sitting
processing class: standing


In [4]:
print(test_labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [5]:
print(train_points)

[[[-3.977e-01  1.745e+00  3.711e-01  0.000e+00  1.300e+02]
  [-1.562e-01  1.894e+00  6.016e-01 -1.252e-01  1.610e+02]
  [-1.782e-01  1.694e+00  5.098e-01 -1.252e-01  1.380e+02]
  ...
  [-1.562e-01  1.816e+00  5.146e-01 -1.252e-01  1.280e+02]
  [-2.437e-01  1.409e+00  5.898e-01 -1.252e-01  1.510e+02]
  [-1.890e-01  1.518e+00  4.072e-01  0.000e+00  1.520e+02]]

 [[-2.109e-01  1.637e+00  6.328e-01  0.000e+00  2.440e+02]
  [-8.838e-02  1.488e+00  3.008e-01  0.000e+00  1.210e+02]
  [-1.782e-01  1.694e+00  5.098e-01 -1.252e-01  1.380e+02]
  ...
  [-1.372e-01  1.773e+00  8.193e-01 -2.505e-01  3.080e+02]
  [-1.372e-01  1.620e+00  6.436e-01  0.000e+00  2.100e+02]
  [-1.372e-01  1.620e+00  6.436e-01  0.000e+00  2.100e+02]]

 [[-4.111e-01  2.320e+00  5.576e-01 -2.505e-01  2.100e+02]
  [-4.045e-01  1.669e+00  3.613e-01  0.000e+00  1.400e+02]
  [-1.006e-01  1.670e+00  5.146e-01 -1.252e-01  1.910e+02]
  ...
  [-6.074e-01  1.410e+00  7.451e-01 -2.505e-01  1.990e+02]
  [-4.658e-01  1.326e+00  5.771e-0

In [6]:
from tensorflow import data as tf_data
import keras
#import PointNET

keras.utils.set_random_seed(seed=42)

In [7]:
train_size = 0.8
dataset = tf_data.Dataset.from_tensor_slices((train_points, train_labels))
test_dataset = tf_data.Dataset.from_tensor_slices((test_points, test_labels))
train_dataset_size = int(len(dataset) * train_size)

In [8]:
dataset = dataset.shuffle(len(train_points)).map(NN.augment)
test_dataset = test_dataset.shuffle(len(test_points)).batch(BATCH_SIZE)
train_dataset = dataset.take(train_dataset_size).batch(BATCH_SIZE)
validation_dataset = dataset.skip(train_dataset_size).batch(BATCH_SIZE)

In [9]:
inputs = keras.Input(shape=(NUM_POINTS, 5))

In [22]:
import matplotlib
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.ticker import LinearLocator
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Conv3D, MaxPooling3D, Embedding, LSTM, Bidirectional, Reshape, Concatenate

In [10]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization

# Define the input shape (5 features)
input_shape = (None, 5)

# Define the model
model = models.Sequential()

# 1. CNN layer
model.add(layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=input_shape))
model.add(layers.MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))
model.add(BatchNormalization())

#model.add(layers.Conv1D(filters=128, kernel_size=3, activation='relu', input_shape=input_shape))
#model.add(layers.MaxPooling1D(pool_size=2))
#model.add(Dropout(0.25))
#model.add(BatchNormalization())

# # 2. LSTM layer
# model.add(layers.LSTM(50, return_sequences=True))
# model.add(layers.LSTM(50))

# 3. Dense layers
#model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
#model.add(BatchNormalization())
#model.add(Dropout(0.5))
#model.add(layers.Dense(1, activation='linear'))  # Output layer (you can adjust the output size and activation)
model.add(layers.Dense(1, activation='softmax'))


In [11]:
# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Summary of the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, None, 64)          1024      
                                                                 
 max_pooling1d (MaxPooling1  (None, None, 64)          0         
 D)                                                              
                                                                 
 dropout (Dropout)           (None, None, 64)          0         
                                                                 
 batch_normalization (Batch  (None, None, 64)          256       
 Normalization)                                                  
                                                                 
 dense (Dense)               (None, None, 64)          4160      
                                                                 
 dense_1 (Dense)             (None, None, 1)           6

Trainable params: 5377 (21.00 KB)
Non-trainable params: 128 (512.00 Byte)
_________________________________________________________________


In [12]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3)
# training
history = model.fit(train_points, train_labels, epochs=30, batch_size=16, validation_data=(test_points, test_labels), verbose=1, callbacks=[early_stopping])

Epoch 1/30
45/45 [==============================] - 2s 10ms/step - loss: 0.5042 - mae: 0.5042 - val_loss: 0.5028 - val_mae: 0.5028
Epoch 2/30
45/45 [==============================] - 0s 5ms/step - loss: 0.5042 - mae: 0.5042 - val_loss: 0.5028 - val_mae: 0.5028
Epoch 3/30
45/45 [==============================] - 0s 5ms/step - loss: 0.5042 - mae: 0.5042 - val_loss: 0.5028 - val_mae: 0.5028
Epoch 4/30
45/45 [==============================] - 0s 5ms/step - loss: 0.5042 - mae: 0.5042 - val_loss: 0.5028 - val_mae: 0.5028


In [13]:
test_loss, test_acc = model.evaluate(test_points, test_labels, verbose=1)

6/6 [==============================] - 0s 3ms/step - loss: 0.5028 - mae: 0.5028


In [14]:
print(test_acc)

0.5027624368667603


In [29]:
# pickle.dump(model, open("model.pkl", "wb"))

In [15]:
# Define the input shape (5 features)
input_shape = (None, 5)

# Define the model
model = models.Sequential()

# 1. CNN layer
model.add(layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=input_shape))
model.add(layers.MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))
model.add(BatchNormalization())

model.add(layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=input_shape))
model.add(layers.MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))
model.add(BatchNormalization())

# Flatten the output
model.add(layers.Flatten())

# Summary of the CNN model
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_1 (Conv1D)           (None, None, 64)          1024      
                                                                 
 max_pooling1d_1 (MaxPoolin  (None, None, 64)          0         
 g1D)                                                            
                                                                 
 dropout_1 (Dropout)         (None, None, 64)          0         
                                                                 
 batch_normalization_1 (Bat  (None, None, 64)          256       
 chNormalization)                                                
                                                                 
 conv1d_2 (Conv1D)           (None, None, 64)          12352     
                                                                 
 max_pooling1d_2 (MaxPoolin  (None, None, 64)         

In [19]:
import numpy as np

# Assuming sequence_length = 100 for this example
sequence_length = 100
X = np.random.random((10, sequence_length, 5))  # Example data

# Extract features using CNN
X_Train_Features = model.predict(train_points)
X_Test_Features = model.predict(test_points)

6/6 [==============================] - 0s 2ms/step


In [23]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

svm_classifer = svm.SVC(kernel='linear')
svm_classifer.fit(X_Train_Features, train_labels)

y_pred = svm_classifer.predict(X_Test_Features)

accuracy = accuracy_score(test_labels, y_pred)
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 99.45


In [26]:
print(len(X_Train_Features))
print(len(X_Test_Features))
print(len(train_labels))
print(len(test_labels))

716
181
716
181
