In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns
import tensorflow as tf
import keras
from sklearn.model_selection import train_test_split
from tensorflow.python.keras.layers.convolutional import Conv1D, MaxPooling1D
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.layers import ConvLSTM2D
from keras.utils import to_categorical
import pickle
import os
import NN

In [70]:
import dataset_utils
import importlib

In [3]:
importlib.reload(dataset_utils)

<module 'dataset_utils' from 'c:\\Users\\cyber\\Desktop\\University\\P4P\\github\\P4P-mmWave\\MMWave_Radar_Human_Tracking_and_Fall_detection\\dataset_utils.py'>

In [71]:
DATA_DIR = "3_class_data"
NUM_POINTS = 100
NUM_CLASSES = 2
BATCH_SIZE = 32
train_points, test_points, train_labels, test_labels, CLASS_MAP = dataset_utils.parse_dataset(NUM_POINTS, DATA_DIR)

processing class: jumping
processing class: speedwalking
processing class: walking


In [72]:
print(test_labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [73]:
print(train_points)

[[[ 8.540e-01  4.612e-01  1.483e-01  2.505e-01  2.050e+02]
  [ 7.290e-01  6.357e-01  4.724e-01  5.010e-01  2.500e+02]
  [ 1.000e+00  8.774e-01  7.404e-02  3.757e-01  3.050e+02]
  ...
  [ 7.437e-01  6.938e-01  2.361e-01  5.010e-01  2.500e+02]
  [ 8.892e-01  4.902e-01  1.000e+00  5.010e-01  3.110e+02]
  [ 6.753e-01  4.902e-01  4.746e-01  3.757e-01  2.820e+02]]

 [[ 4.583e-01  2.130e-01  6.841e-01 -7.515e-01  3.500e+02]
  [ 1.929e-01  3.770e-01  6.641e-01 -3.757e-01  2.900e+02]
  [ 1.929e-01  3.770e-01  6.641e-01 -3.757e-01  2.900e+02]
  ...
  [ 8.950e-01  5.410e-01  5.840e-01  5.010e-01  3.110e+02]
  [ 8.560e-01  2.458e-01  5.532e-01 -5.010e-01  2.940e+02]
  [ 8.623e-01  5.103e-01  2.234e-02  2.505e-01  2.050e+02]]

 [[ 6.709e-01  7.632e-01  5.923e-01 -8.765e-01  2.930e+02]
  [ 1.003e-01  0.000e+00  1.000e+00  6.260e-01  3.340e+02]
  [ 4.287e-01  3.975e-01  4.424e-01 -8.765e-01  2.570e+02]
  ...
  [ 1.109e-01  1.000e+00  4.021e-01 -1.002e+00  3.020e+02]
  [ 4.595e-01  9.468e-01  3.179e-0

In [74]:
from tensorflow import data as tf_data
import keras
#import PointNET

keras.utils.set_random_seed(seed=42)

In [75]:
train_size = 0.8
dataset = tf_data.Dataset.from_tensor_slices((train_points, train_labels))
test_dataset = tf_data.Dataset.from_tensor_slices((test_points, test_labels))
train_dataset_size = int(len(dataset) * train_size)

In [76]:
dataset = dataset.shuffle(len(train_points)).map(NN.augment)
test_dataset = test_dataset.shuffle(len(test_points)).batch(BATCH_SIZE)
train_dataset = dataset.take(train_dataset_size).batch(BATCH_SIZE)
validation_dataset = dataset.skip(train_dataset_size).batch(BATCH_SIZE)

In [77]:
inputs = keras.Input(shape=(NUM_POINTS, 5))

In [11]:
import matplotlib
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.ticker import LinearLocator
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Conv3D, MaxPooling3D, Embedding, LSTM, Bidirectional, Reshape, Concatenate

In [62]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization

# Define the input shape (5 features)
input_shape = (100, 5)

# Define the model
model = models.Sequential()

# 1. CNN layer
model.add(layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=input_shape))
model.add(layers.MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))
model.add(BatchNormalization())

model.add(layers.Dense(3, activation='softmax'))


In [52]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Summary of the model
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_9 (Conv1D)           (None, None, 64)          1024      
                                                                 
 max_pooling1d_9 (MaxPoolin  (None, None, 64)          0         
 g1D)                                                            
                                                                 
 dropout_9 (Dropout)         (None, None, 64)          0         
                                                                 
 batch_normalization_9 (Bat  (None, None, 64)          256       
 chNormalization)                                                
                                                                 
 dense_10 (Dense)            (None, None, 3)           195       
                                                                 
Total params: 1475 (5.76 KB)
Trainable params: 1347 (5

In [53]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3)
# training
history = model.fit(train_points, train_labels, epochs=30, batch_size=16, validation_data=(test_points, test_labels), verbose=1, callbacks=[early_stopping])

Epoch 1/30


ValueError: in user code:

    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1081, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1139, in compute_loss
        return self.compiled_loss(
    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\engine\compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\losses.py", line 142, in __call__
        losses = call_fn(y_true, y_pred)
    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\losses.py", line 268, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\losses.py", line 2122, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "c:\Users\cyber\anaconda3\Lib\site-packages\keras\src\backend.py", line 5560, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None,) and (None, 49, 3) are incompatible


In [45]:
print(train_points.shape)
print(train_labels.shape)
print(test_points.shape)
print(test_labels.shape)

(638, 100, 5)
(638,)
(162, 100, 5)
(162,)


In [38]:
test_loss, test_acc = model.evaluate(test_points, test_labels, verbose=1)

6/6 [==============================] - 0s 2ms/step - loss: 0.7469 - mae: 0.7469


In [63]:
print(test_acc)

0.7469135522842407


In [17]:
# pickle.dump(model, open("model.pkl", "wb"))

In [64]:
# Define the input shape (5 features)
input_shape = (None, 5)

# Define the model
model = models.Sequential()

# 1. CNN layer
model.add(layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=input_shape))
model.add(layers.MaxPooling1D(pool_size=2))
model.add(Dropout(0.25))
model.add(BatchNormalization())

#model.add(layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=input_shape))
#model.add(layers.MaxPooling1D(pool_size=2))
#model.add(Dropout(0.25))
#model.add(BatchNormalization())

#model.add(layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=input_shape))
#model.add(layers.MaxPooling1D(pool_size=2))
#model.add(Dropout(0.25))
#model.add(BatchNormalization())

# Flatten the output
model.add(layers.Flatten())

# Summary of the CNN model
model.summary()


Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_11 (Conv1D)          (None, None, 64)          1024      
                                                                 
 max_pooling1d_11 (MaxPooli  (None, None, 64)          0         
 ng1D)                                                           
                                                                 
 dropout_11 (Dropout)        (None, None, 64)          0         
                                                                 
 batch_normalization_11 (Ba  (None, None, 64)          256       
 tchNormalization)                                               
                                                                 
 flatten_2 (Flatten)         (None, None)              0         
                                                                 
Total params: 1280 (5.00 KB)
Trainable params: 1152 (4

In [65]:
import numpy as np

# Assuming sequence_length = 100 for this example
sequence_length = 100
#X = np.random.random((10, sequence_length, 5))  # Example data

# Extract features using CNN
X_Train_Features = model.predict(train_points)
X_Test_Features = model.predict(test_points)

6/6 [==============================] - 0s 2ms/step


In [66]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

svm_classifer = svm.SVC(kernel='linear')
svm_classifer.fit(X_Train_Features, train_labels)

y_pred = svm_classifer.predict(X_Test_Features)

accuracy = accuracy_score(test_labels, y_pred)
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 38.27


In [67]:
print(len(X_Train_Features))
print(len(X_Test_Features))
print(len(train_labels))
print(len(test_labels))

638
162
638
162


In [68]:
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
svc=svm.SVC(probability=True)
print("The training of the model is started, please wait for while as it may take few minutes to complete")
model=GridSearchCV(svc,param_grid, refit = True, verbose = 4, n_jobs=-1)
model.fit(train_points,train_labels)
print('The Model is trained well with the given images')
model.best_params_

#pickle.dump(model,open('SVM_model.p', 'wb'))
y_pred=model.predict(X_Test_Features)

print(f"The models is {accuracy_score(y_pred,test_labels)*100}% accurate")

The training of the model is started, please wait for while as it may take few minutes to complete
Fitting 5 folds for each of 32 candidates, totalling 160 fits
The Model is trained well with the given images
The models is 41.358024691358025% accurate


In [23]:
with open('SVM_model.p', 'rb') as f:
    model = pickle.load(f)
y_pred = model.predict(X_Test_Features)
accuracy = accuracy_score(test_labels, y_pred)

In [30]:
print(accuracy)

0.3950617283950617


In [ ]:
X_train_flattened = X_Train_Features.reshape(X_Train_Features.shape[0], -1)
X_test_flattened = X_Test_Features.reshape(X_Test_Features.shape[0], -1)

y_train = train_labels.flatten()
y_test = test_labels.flatten()

In [84]:
#pure SVM

param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
svc=svm.SVC(probability=True)
print("The training of the model is started, please wait for while as it may take few minutes to complete")
model=GridSearchCV(svc,param_grid, refit = True, verbose = 4, n_jobs=-1)
model.fit(train_points,train_labels)
print('The Model is trained well with the given images')
model.best_params_

y_pred=model.predict(test_points)

print(f"The models is {accuracy_score(y_pred,test_labels)*100}% accurate")

The training of the model is started, please wait for while as it may take few minutes to complete
Fitting 5 folds for each of 32 candidates, totalling 160 fits
The Model is trained well with the given images


TypeError: float() argument must be a string or a real number, not '_BatchDataset'

In [83]:
y_pred = svm_classifier.predict(X_Test_Features)

accuracy = accuracy_score(test_labels, y_pred)
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 55.56
