In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns
import tensorflow as tf
import keras
from sklearn.model_selection import train_test_split
from tensorflow.python.keras.layers.convolutional import Conv1D, MaxPooling1D
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.layers import ConvLSTM2D
from keras.utils import to_categorical
import pickle
import os
import dataset_utils
import NN

In [59]:
import dataset_utils

In [3]:
def flatten_and_pad(point_cloud, target_length):
    # Flatten the point cloud into a 2D array with X, Y, Z coordinates
    # Ensure the data is padded or truncated to match the target length
    num_points = len(point_cloud)
    padded_point_cloud = np.zeros((target_length, 3))
    padded_point_cloud[:num_points] = point_cloud
    return padded_point_cloud

In [49]:
DATA_DIR = "model_data"
NUM_POINTS = 40
NUM_CLASSES = 2
BATCH_SIZE = 32
train_points, test_points, train_labels, test_labels, CLASS_MAP = dataset_utils.parse_dataset(NUM_POINTS, DATA_DIR)

processing class: sit
processing class: stand


In [50]:
print(train_points)

[[[-2.025e+00  2.991e-01  1.513e+00  0.000e+00  1.350e+02]
  [-2.902e+00  1.609e+00  7.598e-01  2.505e-01  1.660e+02]
  [-1.616e-01  1.748e+00  7.031e-01  3.757e-01  2.290e+02]
  ...
  [-2.152e+00  2.051e+00  8.672e-01  0.000e+00  2.130e+02]
  [-2.152e+00  2.049e+00  8.662e-01  0.000e+00  2.130e+02]
  [-1.743e-01  1.755e+00  7.842e-01  5.010e-01  2.400e+02]]

 [[ 1.078e+00  3.805e+00  1.090e+00  1.252e-01  2.440e+02]
  [-2.090e-01  2.428e+00  1.973e-01 -3.757e-01  1.730e+02]
  [-1.049e+00  4.297e-01  3.688e+00  0.000e+00  1.260e+02]
  ...
  [ 6.455e-01  5.156e-01 -3.184e-01  0.000e+00  1.250e+02]
  [ 1.070e+00  3.805e+00  1.146e+00  1.252e-01  3.250e+02]
  [-7.129e-02  2.768e+00 -1.563e-02  3.757e-01  2.750e+02]]

 [[ 1.103e+00  3.969e+00  8.203e-01 -1.252e-01  2.150e+02]
  [ 1.110e+00  3.918e+00  7.988e-01 -5.010e-01  2.020e+02]
  [ 6.455e-01  5.117e-01 -3.125e-01  0.000e+00  1.230e+02]
  ...
  [ 6.455e-01  4.062e-01 -1.309e-01  0.000e+00  1.180e+02]
  [ 7.998e-01  3.945e+00  9.023e-0

In [51]:
from tensorflow import data as tf_data
import keras
import PointNET

keras.utils.set_random_seed(seed=42)

In [52]:
train_size = 0.8
dataset = tf_data.Dataset.from_tensor_slices((train_points, train_labels))
test_dataset = tf_data.Dataset.from_tensor_slices((test_points, test_labels))
train_dataset_size = int(len(dataset) * train_size)

In [53]:
dataset = dataset.shuffle(len(train_points)).map(NN.augment)
test_dataset = test_dataset.shuffle(len(test_points)).batch(BATCH_SIZE)
train_dataset = dataset.take(train_dataset_size).batch(BATCH_SIZE)
validation_dataset = dataset.skip(train_dataset_size).batch(BATCH_SIZE)

In [54]:
inputs = keras.Input(shape=(NUM_POINTS, 5))

In [55]:
def model_structure_1D(input_shape, output_shape):
    _model_input = Input(shape=input_shape)
    _model = Conv1D(32, kernel_size=1, padding='same', activation='relu')(_model_input)
    _model = MaxPooling1D(pool_size=2)(_model)
    _model = Flatten()(_model)
    _model = Dense(output_shape, activation='softmax')(_model)
    model = Model(inputs=_model_input, outputs=_model)
    return model


In [56]:
import matplotlib
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.ticker import LinearLocator
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Conv3D, MaxPooling3D, Embedding, LSTM, Bidirectional, Reshape, Concatenate

In [57]:
input_shape = (40, 5)  # Example input shape for 3D data
output_shape = 3  # Number of classes or output units
model = model_structure_1D(input_shape, output_shape)

AttributeError: 'tuple' object has no attribute 'rank'